# Generated by Django 5.2.1 on 2026-04-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(default='urgent_help', max_length=80)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_date', models.DateField()),
                ('fever', models.BooleanField(default=False)),
                ('nausea', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('severe_pain', models.BooleanField(default=False)),
                ('breathing_difficulty', models.BooleanField(default=False)),
                ('dizziness', models.BooleanField(default=False)),
                ('bleeding', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('appetite_loss', models.BooleanField(default=False)),
                ('infection_signs', models.BooleanField(default=False)),
                ('symptom_severity_score', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-symptom_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pain_level', models.PositiveSmallIntegerField(default=0)),
                ('fatigue_level', models.PositiveSmallIntegerField(default=0)),
                ('appetite_level', models.PositiveSmallIntegerField(default=5)),
                ('recorded_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
