# Generated by Django 5.2.1 on 2026-04-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('treatment', 'Treatment'), ('scan', 'Scan'), ('lab_test', 'Lab test'), ('follow_up', 'Follow up'), ('other', 'Other')], default='consultation', max_length=30)),
                ('hospital_name', models.CharField(blank=True, max_length=180)),
                ('doctor_name', models.CharField(blank=True, max_length=160)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
