# Generated by Django 5.2.1 on 2026-06-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fast_mode',
            field=models.BooleanField(default=True),
        ),
    ]
