# Generated by Django 5.2.1 on 2026-05-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='grace_period_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
