# Generated by Django 5.2.1 on 2026-04-29 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverlink',
            name='caregiver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'caregiver'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caregiverlink',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='caregiverlink',
            index=models.Index(fields=['invite_code'], name='linking_car_invite__adb65c_idx'),
        ),
        migrations.AddIndex(
            model_name='caregiverlink',
            index=models.Index(fields=['status'], name='linking_car_status_5c02af_idx'),
        ),
    ]
