# Generated by Django 5.2.1 on 2026-04-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveSmallIntegerField()),
                ('risk_category', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('reasons', models.JSONField(default=list)),
                ('suggested_action', models.TextField()),
                ('disclaimer', models.TextField()),
                ('input_snapshot', models.JSONField(default=dict)),
                ('model_version', models.CharField(default='rule-based-v1', max_length=80)),
                ('rule_score', models.PositiveSmallIntegerField(default=0)),
                ('ml_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
